### PR TITLE
Enables multiple outputs for conversion to tensorflow

### PR DESCRIPTION
**Pull request by SmokerX**
solve the problem[https://github.com/microsoft/MMdnn/issues/759](url)

### CODE REVIEW

**Comment by SmokerX** [comment]
@rainLiuplus 
I am sorry that this PR did not pass the automatic test, but I looked at the test case that was not passed, and it is related to keras and mxnet, but my modification is only related to tensorflow, and it is the last step of the conversion process, based on the py generating tensorflow. Processing after the file.
I would like to ask you to see if there is a problem with this test case.

**Comment by rainLiuplus** [comment]
Hi @SmokerX, thanks for your contributions!
The test cases you mentioned have been restarted. They are often out of memory and out of time due to the limitations of Travis platform.

**Comment by SmokerX** [comment]
@rainLiuplus 
I notice that this automatic has finished 14 minutes ago, but you said those test cases had been restarted 34 minutes ago. The status of automatic test is finished now.  Did they really restart?

**Comment by rainLiuplus** [comment]
@SmokerX, sorry, I do not understand your meaning. I manually restarted the test cases.

**Comment by SmokerX** [comment]
@rainLiuplus 
OK, these test cases are running now.

**Comment by SmokerX** [comment]
@rainLiuplus 
It seems to be out of memory again...

**Comment by SmokerX** [comment]
@rainLiuplus 
There are still 2 test cases left this time.

**Comment by rainLiuplus** [comment]
The tests are all passed now.

**Pull request merged**
