### PR TITLE
fix caffe to tensorflow (#566)

### PR DESCRIPTION
**Pull request by SmokerX**

### CODE REVIEW

**Comment by SmokerX** [comment]
> Hi @SmokerX , restarted, thanks for the contributing!

@rainLiuplus I am sorry that the result is the same. Can you please provide the test code for this case so that I can upload it after debugging locally?

**Comment by rainLiuplus** [comment]
Hi @SmokerX , the test files are under `tests` directory; you can run `tests/test_caffe.py` to test all caffe models. Thanks!

**Comment by SmokerX** [comment]
@rainLiuplus I noticed a recent pr([Split test case to reduce travis build time](https://github.com/Microsoft/MMdnn/pull/568)), just beacuse the case of my yesterday's case failed was a timeout, so i resubmitted it again, and yesterday the case passed smoothly, but the another case [Job#518.48](https://travis-ci.org/Microsoft/MMdnn/jobs/480692741) was given an error, I checked the wrong content, as follows:
```
3.5 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.5.tar.bz2
$ curl -sSf -o python-3.5.tar.bz2 ${archive_url}
curl: (7) Failed to connect to s3.amazonaws.com port 443: Connection timed out
Unable to download 3.5 archive. The archive may not exist. Please consider a different version.
after_failure
0.00s$ true
```

But I think this shuold not be my problem. Can you help me solve it?

**Comment by SmokerX** [comment]
@rainLiuplus I am very happy that all the cases have passed. Can my code be merged?

**Pull request merged**
